# Generated by Django 6.0.2 on 2026-02-11 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_language", models.CharField(max_length=50)),
                ("stage_activity", models.CharField(max_length=50)),
                ("extempore_comfort", models.IntegerField()),
                ("public_speaking_confidence", models.IntegerField()),
                ("help_seeking_comfort", models.IntegerField()),
                ("group_discussion_confidence", models.IntegerField()),
                ("adaptability", models.IntegerField()),
                ("total_score", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
